//! Turns internal tasks into a complete `VCALENDAR` document.

use std::collections::BTreeMap;

use chrono::{DateTime, NaiveDateTime, TimeZone, Utc};
use icalendar::{
    Alarm, Calendar, CalendarDateTime, Component, DatePerhapsTime, EventLike, Property, Todo,
    TodoStatus, Trigger,
};

use crate::{
    config::{CalendarConfig, RemindersConfig},
    model::{CalendarValue, Task},
    reminder::reminders_for,
};

#[derive(Debug, thiserror::Error)]
pub enum RenderError {
    /// Two tasks produced one UID. Publishing that would make a calendar
    /// client silently drop one of them, so the whole render fails instead.
    #[error("duplicate UID {uid} generated by objects {first} and {second}")]
    DuplicateUid {
        uid: String,
        first: String,
        second: String,
    },
}

/// Which Anytype property a date on the wire came from. Writing a change back
/// has to land in the same place, or moving a card in a calendar would turn a
/// planned date into a deadline.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Origin {
    Scheduled,
    Deadline,
    /// An all-day plan and deadline on one day, collapsed into one `DUE`.
    Both,
}

/// A task's dates as a calendar client receives them, with their origins.
#[derive(Debug, Clone, PartialEq)]
pub struct Wire {
    pub start: Option<(DatePerhapsTime, Origin)>,
    pub due: Option<(DatePerhapsTime, Origin)>,
}

/// What a task's two dates become on the wire.
enum Schedule {
    Neither,
    Due(DatePerhapsTime, Origin),
    Both {
        start: DatePerhapsTime,
        due: DatePerhapsTime,
    },
    /// The deadline cannot be written beside the plan — either the work is
    /// planned after it, or it is a whole day the plan already sits inside — so
    /// the plan is written and the deadline is described in words.
    Described {
        due: DatePerhapsTime,
        deadline: String,
    },
}

/// Gives a VALARM the UID and DTSTAMP it would otherwise get from the
/// library: a random UUID and the current time on every serialisation, which
/// changes the resource's ETag on each render.
pub fn stable_alarm(
    mut alarm: Alarm,
    owner_uid: &str,
    index: usize,
    stamp: DateTime<Utc>,
) -> Alarm {
    alarm
        .add_property("UID", format!("{owner_uid}-alarm-{index}"))
        .timestamp(stamp);
    alarm.done()
}

/// SEQUENCE for a component last modified at `modified`.
///
/// Calino increments SEQUENCE when it edits a task and, with its default
/// "server wins" setting, takes the server's copy only when the server's
/// SEQUENCE is not lower than its own (`useCalDAV.ts` sync reconciliation).
/// Without the property the server reads as 0, so after one edit in Calino
/// later edits made in Anytype would never reach the calendar. Seconds since
/// the epoch only grow with each Anytype write and stay far above Calino's
/// small counters.
pub fn sequence_for(modified: DateTime<Utc>) -> u32 {
    u32::try_from(modified.timestamp().max(0)).unwrap_or(u32::MAX)
}

pub struct VTodoRenderer {
    config: CalendarConfig,
    reminders: RemindersConfig,
    /// Used as `DTSTAMP` for tasks whose last-modified time Anytype did not
    /// report. Fixed for the life of the process so that repeated requests
    /// produce byte-identical output, which keeps the ETag stable.
    fallback_stamp: DateTime<Utc>,
}

/// The link that opens an object in the Anytype app itself. The web link the
/// API gives (`https://object.any.coop/<id>?spaceId=<space>`) lands on a page
/// with an "Open in App" button first; the app's own scheme skips it. A link
/// of any other shape is passed through as it is.
pub fn app_link(web_link: &str) -> String {
    web_link
        .strip_prefix("https://object.any.coop/")
        .and_then(|rest| rest.split_once("?spaceId="))
        .map(|(object_id, space_id)| {
            let space_id = space_id.split(['&', '#']).next().unwrap_or(space_id);
            format!("anytype://object?objectId={object_id}&spaceId={space_id}")
        })
        .unwrap_or_else(|| web_link.to_string())
}

impl VTodoRenderer {
    pub fn new(
        config: CalendarConfig,
        reminders: RemindersConfig,
        fallback_stamp: DateTime<Utc>,
    ) -> Self {
        Self {
            config,
            reminders,
            fallback_stamp,
        }
    }

    pub fn render(&self, tasks: &[Task]) -> Result<String, RenderError> {
        // Sorting by UID makes the output deterministic, so identical source
        // data always hashes to the same ETag.
        let mut by_uid: BTreeMap<String, &Task> = BTreeMap::new();
        for task in tasks {
            let uid = task.uid();
            if let Some(existing) = by_uid.get(&uid) {
                return Err(RenderError::DuplicateUid {
                    uid,
                    first: existing.object_id.clone(),
                    second: task.object_id.clone(),
                });
            }
            by_uid.insert(uid, task);
        }

        let mut calendar = self.calendar();
        for task in by_uid.values() {
            calendar.push(self.render_task(task));
        }

        Ok(calendar.to_string())
    }

    /// One `VCALENDAR` per task, keyed by object id: the resources of a CalDAV
    /// collection. Each body is exactly what the feed would contain for that
    /// task, so both views agree byte for byte on the component.
    pub fn render_each(&self, tasks: &[Task]) -> Vec<(String, String)> {
        tasks
            .iter()
            .map(|task| {
                let mut calendar = self.calendar();
                calendar.push(self.render_task(task));
                (task.object_id.clone(), calendar.to_string())
            })
            .collect()
    }

    fn calendar(&self) -> Calendar {
        let mut calendar = Calendar::new();
        calendar
            .name(&self.config.name)
            .timezone(self.config.timezone.name())
            .append_property(Property::new("PRODID", "-//Anytype Task Exporter//EN"))
            .append_property(Property::new("VERSION", "2.0"))
            .append_property(Property::new("CALSCALE", "GREGORIAN"));
        calendar
    }

    fn render_task(&self, task: &Task) -> Todo {
        let mut todo = Todo::new();
        let modified = task.last_modified.unwrap_or(self.fallback_stamp);
        todo.uid(&task.uid())
            .summary(&task.name)
            .timestamp(modified)
            .sequence(sequence_for(modified));

        // What a client shows under the title. Nothing here is read back on a
        // write, so it can carry what the calendar has no property for.
        let mut description: Vec<String> = Vec::new();

        let tz = self.config.date_only_timezone;
        match self.schedule(
            task.scheduled.as_ref().map(|value| value.classify(tz)),
            task.deadline.as_ref().map(|value| value.classify(tz)),
        ) {
            Schedule::Neither => {}
            Schedule::Due(due, _) => {
                todo.due(due);
            }
            Schedule::Both { start, due } => {
                todo.starts(start).due(due);
            }
            Schedule::Described { due, deadline } => {
                todo.due(due);
                description.push(deadline);
            }
        }

        if task.done {
            todo.status(TodoStatus::Completed).percent_complete(100);
            // No COMPLETED property: Anytype's checkbox records *that* a task
            // is done, not *when*. Substituting last-modified would invent a
            // timestamp the source never supplied.
        } else {
            todo.status(TodoStatus::NeedsAction).percent_complete(0);
        }

        if let Some(url) = &task.object_url {
            todo.url(url);
            // Also in the description, on a line of its own: a client shows
            // `URL` in few places, if at all, and makes a link of this one.
            description.push(app_link(url));
        }
        if !description.is_empty() {
            todo.description(&description.join("\n"));
        }

        let mut todo = todo.done();
        // One CATEGORIES line per tag. A single comma-joined line would be
        // escaped as TEXT (RFC 5545 §3.3.11) and read back as one category whose
        // name contains commas; RFC 5545 §3.8.1.2 allows the property to repeat,
        // and Calino reads every line.
        for tag in &task.tags {
            todo.add_multi_property("CATEGORIES", tag);
        }
        for (index, alarm) in self.alarms_for(task).into_iter().enumerate() {
            todo.alarm(stable_alarm(alarm, &task.uid(), index, modified));
        }
        todo
    }

    /// Builds the `VALARM`s, if any.
    ///
    /// Every trigger is an absolute instant. A relative trigger on a `VTODO`
    /// resolves against `DTSTART` unless `RELATED=END` is given, and an all-day
    /// task starts at midnight, so "30 minutes before" would fire at 23:30 the
    /// night before. Computing the instant here removes that ambiguity.
    fn alarms_for(&self, task: &Task) -> Vec<Alarm> {
        reminders_for(task, &self.config, &self.reminders)
            .into_iter()
            .map(|moment| {
                Alarm::display(
                    &task.name,
                    Trigger::DateTime(CalendarDateTime::Utc(moment.trigger_at)),
                )
                .done()
            })
            .collect()
    }

    /// Resolves the two source dates into a pair a calendar client will accept.
    ///
    /// RFC 5545 §3.6.2 requires `DUE` to share `DTSTART`'s value type and to be
    /// later in time than it. Anytype constrains neither, so three shapes need
    /// care: a date-only deadline against a timed start (the common one, since
    /// such a deadline means the *end* of its day while `VALUE=DATE` reads as
    /// the start), an all-day pair on a single day, and work genuinely planned
    /// after its deadline. Emitting the invalid pair is the worst option
    /// available — a client drops the task from the calendar altogether.
    fn schedule(
        &self,
        scheduled: Option<CalendarValue>,
        deadline: Option<CalendarValue>,
    ) -> Schedule {
        let (start, due) = match (scheduled, deadline) {
            (None, None) => return Schedule::Neither,
            // A planned date with no deadline is written as `DUE` alone. Calino
            // buckets tasks into days by that property and by nothing else, so a
            // `DTSTART`-only task is parsed, kept, and never drawn — while its
            // parser reads `start` back off `DUE` when `DTSTART` is absent
            // (`start = DTSTART || DUE`), so the hour survives the omission.
            (Some(start), None) => {
                return Schedule::Due(self.to_calendar_date(start), Origin::Scheduled);
            }
            (None, Some(due)) => {
                return Schedule::Due(self.to_calendar_date(due), Origin::Deadline);
            }
            (Some(start), Some(due)) => (start, due),
        };

        // Planning work after its own deadline is legitimate — the deadline was
        // missed and the task is being done late — but iCalendar cannot say it.
        // The start survives because it is the date to act on, and the deadline
        // moves into DESCRIPTION rather than vanishing.
        if self.begins(start) >= self.expires(due) {
            // The plan still has to supply a day, or a client that files tasks
            // by `DUE` drops it exactly as it dropped the invalid pair.
            return Schedule::Described {
                due: self.to_calendar_date(start),
                deadline: self.describe(due),
            };
        }

        match (start, due) {
            // One all-day value cannot precede another on the same day, and the
            // start would say nothing the deadline does not.
            (CalendarValue::AllDay(from), CalendarValue::AllDay(to)) if from == to => {
                Schedule::Due(self.to_calendar_date(due), Origin::Both)
            }
            (CalendarValue::AllDay(_), CalendarValue::AllDay(_))
            | (CalendarValue::Instant(_), CalendarValue::Instant(_)) => Schedule::Both {
                start: self.to_calendar_date(start),
                due: self.to_calendar_date(due),
            },
            // A whole-day deadline on the day the work is planned says nothing
            // the planned instant does not already say. Written literally the
            // pair has to stretch the deadline to 23:59:59, and a client that
            // files by `DUE` then shows that second while drawing the card at
            // `DTSTART` — one task reading as two different times. Keep the
            // instant that is actionable and describe the deadline.
            (CalendarValue::Instant(_), CalendarValue::AllDay(day))
                if self.begins(start).date() == day =>
            {
                Schedule::Described {
                    due: self.to_calendar_date(start),
                    deadline: self.describe(due),
                }
            }
            // Mixed value types with a sound order: express both as instants so
            // the deadline keeps its "by the end of that day" meaning instead of
            // collapsing onto midnight.
            _ => match (
                self.instant(self.begins(start)),
                self.instant(self.expires(due)),
            ) {
                (Some(start), Some(due)) => Schedule::Both {
                    start: DatePerhapsTime::DateTime(CalendarDateTime::Utc(start)),
                    due: DatePerhapsTime::DateTime(CalendarDateTime::Utc(due)),
                },
                // A DST gap swallowed one of the civil times; the deadline alone
                // is still valid and is the more important of the two.
                _ => Schedule::Due(self.to_calendar_date(due), Origin::Deadline),
            },
        }
    }

    pub fn config(&self) -> &CalendarConfig {
        &self.config
    }

    /// The dates a client sees for `task`, and where each came from.
    pub fn wire(&self, task: &Task) -> Wire {
        let tz = self.config.date_only_timezone;
        match self.schedule(
            task.scheduled.as_ref().map(|value| value.classify(tz)),
            task.deadline.as_ref().map(|value| value.classify(tz)),
        ) {
            Schedule::Neither => Wire {
                start: None,
                due: None,
            },
            Schedule::Due(due, origin) => Wire {
                start: None,
                due: Some((due, origin)),
            },
            Schedule::Both { start, due } => Wire {
                start: Some((start, Origin::Scheduled)),
                due: Some((due, Origin::Deadline)),
            },
            // The deadline is only described in words; the wire date is the plan.
            Schedule::Described { due, .. } => Wire {
                start: None,
                due: Some((due, Origin::Scheduled)),
            },
        }
    }

    /// One task as a complete `VCALENDAR`, as a CalDAV resource carries it.
    pub fn render_one(&self, task: &Task) -> String {
        let mut calendar = self.calendar();
        calendar.push(self.render_task(task));
        calendar.to_string()
    }

    /// The civil moment a value starts covering.
    fn begins(&self, value: CalendarValue) -> NaiveDateTime {
        match value {
            CalendarValue::AllDay(day) => day.and_hms_opt(0, 0, 0).expect("midnight exists"),
            CalendarValue::Instant(at) => at.with_timezone(&self.config.timezone).naive_local(),
        }
    }

    /// The last civil moment at which a value is still met. An all-day deadline
    /// runs to the end of its day, which is the whole reason a task planned for
    /// noon can share that day with it.
    fn expires(&self, value: CalendarValue) -> NaiveDateTime {
        match value {
            CalendarValue::AllDay(day) => day.and_hms_opt(23, 59, 59).expect("last second exists"),
            CalendarValue::Instant(at) => at.with_timezone(&self.config.timezone).naive_local(),
        }
    }

    fn instant(&self, local: NaiveDateTime) -> Option<DateTime<Utc>> {
        self.config
            .timezone
            .from_local_datetime(&local)
            .earliest()
            .map(|at| at.with_timezone(&Utc))
    }

    fn describe(&self, deadline: CalendarValue) -> String {
        match deadline {
            CalendarValue::AllDay(day) => format!("Дедлайн: {}", day.format("%d.%m.%Y")),
            CalendarValue::Instant(at) => format!(
                "Дедлайн: {}",
                at.with_timezone(&self.config.timezone)
                    .format("%d.%m.%Y %H:%M")
            ),
        }
    }

    fn to_calendar_date(&self, value: CalendarValue) -> DatePerhapsTime {
        match value {
            CalendarValue::AllDay(date) => DatePerhapsTime::Date(date),
            CalendarValue::Instant(dt) => DatePerhapsTime::DateTime(CalendarDateTime::Utc(dt)),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;
    use chrono_tz::Europe::Saratov;

    use crate::model::AnytypeDate;

    fn calendar_config() -> CalendarConfig {
        CalendarConfig {
            timezone: Saratov,
            name: "Anytype Tasks".into(),
            date_only_timezone: Saratov,
        }
    }

    fn reminders() -> RemindersConfig {
        RemindersConfig {
            enabled: true,
            lead_time: chrono::Duration::minutes(30),
            all_day_time: chrono::NaiveTime::from_hms_opt(9, 0, 0).unwrap(),
        }
    }

    fn renderer() -> VTodoRenderer {
        renderer_with(reminders())
    }

    fn renderer_with(reminders: RemindersConfig) -> VTodoRenderer {
        VTodoRenderer::new(
            calendar_config(),
            reminders,
            Utc.with_ymd_and_hms(2026, 1, 1, 0, 0, 0).unwrap(),
        )
    }

    fn task(id: &str, name: &str) -> Task {
        Task {
            object_id: id.into(),
            name: name.into(),
            scheduled: None,
            deadline: None,
            done: false,
            reminder_leads: Vec::new(),
            tags: Vec::new(),
            assignees: Vec::new(),
            ical_uid: None,
            object_url: None,
            last_modified: None,
        }
    }

    fn date(raw: &str) -> Option<AnytypeDate> {
        AnytypeDate::parse(raw)
    }

    /// Calino files tasks into days by `DUE` alone — a `DTSTART`-only task is
    /// parsed and then never drawn. 139 of 281 real tasks were invisible for
    /// exactly this reason. The plan therefore goes to `DUE`, and only there:
    /// its parser reads `start = DTSTART || DUE`, so the hour survives, while a
    /// second property could only disagree with the first.
    #[test]
    fn the_description_link_opens_the_app_directly() {
        assert_eq!(
            app_link("https://object.any.coop/bafyobj?spaceId=bafyspace.abc"),
            "anytype://object?objectId=bafyobj&spaceId=bafyspace.abc"
        );
        // An invite link carries more after the space; only the space is kept.
        assert_eq!(
            app_link("https://object.any.coop/bafyobj?spaceId=bafyspace.abc&inviteId=x#key"),
            "anytype://object?objectId=bafyobj&spaceId=bafyspace.abc"
        );
        assert_eq!(
            app_link("anytype://object?objectId=a"),
            "anytype://object?objectId=a"
        );
    }

    #[test]
    fn a_planned_time_with_no_deadline_is_written_as_due_alone() {
        let mut t = task("plan", "Записаться на обклейку электроники в гитаре");
        t.scheduled = date("2026-08-31T14:00:00+04:00");

        let ics = renderer().render(&[t]).unwrap();

        assert!(ics.contains("DUE:20260831T100000Z"), "{ics}");
        assert!(!ics.contains("DTSTART"), "{ics}");
        // Nothing invents an end of day the source never gave.
        assert!(!ics.contains("195959"), "{ics}");
    }

    /// An all-day plan has no hour worth keeping, and `DTSTART` equal to `DUE`
    /// is invalid, so the day alone is written.
    #[test]
    fn an_all_day_plan_is_written_as_the_day_alone() {
        let mut t = task("plan-day", "Перезаписаться на обследование");
        t.scheduled = date("2026-08-31T00:00:00+04:00");

        let ics = renderer().render(&[t]).unwrap();

        assert!(ics.contains("DUE;VALUE=DATE:20260831"), "{ics}");
        assert!(!ics.contains("DTSTART"), "{ics}");
    }

    /// Observed live: Anytype happily holds "planned today at noon, due today".
    /// A date-only DUE reads as that day's *midnight*, so the pair looks
    /// backwards and Calino refused to display five such tasks; stretching the
    /// deadline to 23:59:59 fixed that but made the card read 12:00 in the grid
    /// and 23:59 when opened. The whole day adds nothing the noon does not, so
    /// only the actionable instant is written.
    #[test]
    fn a_whole_day_deadline_around_the_plan_defers_to_it() {
        let mut t = task("ozon", "Проверить кредитку Ozon");
        t.scheduled = date("2026-08-28T12:00:00+04:00");
        t.deadline = date("2026-08-28T00:00:00+04:00");

        let ics = renderer().render(&[t]).unwrap();

        assert!(ics.contains("DUE:20260828T080000Z"), "{ics}");
        // No second time to contradict it, and the deadline is not lost.
        assert!(!ics.contains("DTSTART"), "{ics}");
        assert!(ics.contains("DESCRIPTION:Дедлайн: 28.08.2026"), "{ics}");
        assert!(!ics.contains("195959"), "{ics}");
    }

    /// Missing a deadline and planning the work late is a real state, and one
    /// iCalendar cannot express. The actionable date is kept; the deadline is
    /// described rather than dropped.
    #[test]
    fn work_planned_after_its_deadline_keeps_the_date_to_act_on() {
        let mut t = task("late", "Сделай self-review статьи");
        t.scheduled = date("2026-07-28T19:00:00+04:00");
        t.deadline = date("2026-07-15T00:00:00+04:00");

        let ics = renderer().render(&[t]).unwrap();

        // The day comes from the plan, so the task is filed where it can be
        // acted on instead of vanishing.
        assert!(ics.contains("DUE:20260728T150000Z"), "{ics}");
        assert!(!ics.contains("DTSTART"), "{ics}");
        assert!(ics.contains("DESCRIPTION:Дедлайн: 15.07.2026"), "{ics}");
    }

    /// Two all-day values on one day cannot be ordered, and the start would say
    /// nothing the deadline does not.
    #[test]
    fn an_all_day_pair_on_one_day_is_written_as_the_deadline_alone() {
        let mut t = task("sber", "Проверить кредитку Сбера");
        t.scheduled = date("2026-08-31T00:00:00+04:00");
        t.deadline = date("2026-08-31T00:00:00+04:00");

        let ics = renderer().render(&[t]).unwrap();

        assert!(ics.contains("DUE;VALUE=DATE:20260831"), "{ics}");
        assert!(!ics.contains("DTSTART"), "{ics}");
    }

    #[test]
    fn emits_the_expected_calendar_properties() {
        let ics = renderer().render(&[task("a", "One")]).unwrap();
        assert!(ics.contains("VERSION:2.0"), "{ics}");
        assert!(ics.contains("PRODID:-//Anytype Task Exporter//EN"), "{ics}");
        assert!(ics.contains("CALSCALE:GREGORIAN"), "{ics}");
        assert!(ics.contains("X-WR-CALNAME:Anytype Tasks"), "{ics}");
        assert!(ics.contains("X-WR-TIMEZONE:Europe/Saratov"), "{ics}");
        assert!(ics.starts_with("BEGIN:VCALENDAR"), "{ics}");
        assert!(ics.trim_end().ends_with("END:VCALENDAR"), "{ics}");
    }

    #[test]
    fn an_active_task_needs_action() {
        let ics = renderer().render(&[task("a", "One")]).unwrap();
        assert!(ics.contains("STATUS:NEEDS-ACTION"), "{ics}");
        assert!(ics.contains("PERCENT-COMPLETE:0"), "{ics}");
    }

    #[test]
    fn each_tag_is_its_own_category_line() {
        let mut tagged = task("a", "One");
        tagged.tags = vec!["Финансы".into(), "Дом, дача".into()];
        let ics = renderer().render(&[tagged]).unwrap();
        assert!(ics.contains("CATEGORIES:Финансы\r\n"), "{ics}");
        // The comma inside a name is escaped, so it stays one category.
        assert!(ics.contains("CATEGORIES:Дом\\, дача\r\n"), "{ics}");
    }

    #[test]
    fn an_untagged_task_has_no_categories() {
        let ics = renderer().render(&[task("a", "One")]).unwrap();
        assert!(!ics.contains("CATEGORIES"), "{ics}");
    }

    /// Calino keeps a server copy only if its SEQUENCE is not below its own
    /// edit counter; a later Anytype write must win again.
    #[test]
    fn sequence_grows_with_every_anytype_write() {
        let mut t = task("a", "One");
        t.last_modified = Some(Utc.with_ymd_and_hms(2026, 9, 15, 12, 0, 0).unwrap());
        let first = renderer().render_one(&t);
        assert!(first.contains("SEQUENCE:1789473600\r\n"), "{first}");
        t.last_modified = Some(Utc.with_ymd_and_hms(2026, 9, 15, 12, 0, 5).unwrap());
        assert!(
            renderer()
                .render_one(&t)
                .contains("SEQUENCE:1789473605\r\n")
        );
    }

    #[test]
    fn a_done_task_is_completed() {
        let mut done = task("a", "One");
        done.done = true;
        let ics = renderer().render(&[done]).unwrap();
        assert!(ics.contains("STATUS:COMPLETED"), "{ics}");
        assert!(ics.contains("PERCENT-COMPLETE:100"), "{ics}");
    }

    /// Anytype records *that* a task is done, never *when*. Inventing the
    /// timestamp would be worse than omitting the property.
    #[test]
    fn never_fabricates_a_completed_timestamp() {
        let mut done = task("a", "One");
        done.done = true;
        done.last_modified = Some(Utc.with_ymd_and_hms(2026, 8, 29, 12, 0, 0).unwrap());
        let ics = renderer().render(&[done]).unwrap();
        assert!(!ics.contains("COMPLETED:"), "{ics}");
    }

    #[test]
    fn never_emits_recurrence() {
        let ics = renderer()
            .render(&[task("a", "One"), task("b", "Two")])
            .unwrap();
        assert!(!ics.contains("RRULE"), "{ics}");
        assert!(!ics.contains("RDATE"), "{ics}");
    }

    /// A `TZID` parameter would oblige the document to carry a matching
    /// `VTIMEZONE` component (RFC 5545 §3.6.5). Emitting UTC instants avoids
    /// the requirement entirely, so neither may ever appear.
    #[test]
    fn never_emits_tzid_or_vtimezone() {
        let mut t = task("a", "One");
        t.scheduled = date("2026-08-29T14:30:00+04:00");
        t.deadline = date("2026-08-30T18:00:00+04:00");
        let ics = renderer().render(&[t]).unwrap();
        assert!(!ics.contains("TZID="), "{ics}");
        assert!(!ics.contains("BEGIN:VTIMEZONE"), "{ics}");
    }

    #[test]
    fn midnight_becomes_a_date_value() {
        let mut t = task("a", "One");
        t.scheduled = date("2026-08-29T00:00:00+04:00");
        t.deadline = date("2026-08-30T00:00:00+04:00");
        let ics = renderer().render(&[t]).unwrap();
        assert!(ics.contains("DTSTART;VALUE=DATE:20260829"), "{ics}");
        assert!(ics.contains("DUE;VALUE=DATE:20260830"), "{ics}");
    }

    #[test]
    fn a_time_of_day_becomes_a_utc_instant() {
        let mut t = task("a", "One");
        t.scheduled = date("2026-08-29T14:30:00+04:00");
        let ics = renderer().render(&[t]).unwrap();
        assert!(ics.contains("DUE:20260829T103000Z"), "{ics}");
    }

    #[test]
    fn a_task_without_dates_stays_undated() {
        let ics = renderer().render(&[task("a", "One")]).unwrap();
        assert!(!ics.contains("DTSTART"), "{ics}");
        assert!(!ics.contains("DUE"), "{ics}");
    }

    #[test]
    fn components_are_ordered_by_uid_regardless_of_input_order() {
        let forward = renderer()
            .render(&[task("a", "A"), task("b", "B"), task("c", "C")])
            .unwrap();
        let reversed = renderer()
            .render(&[task("c", "C"), task("b", "B"), task("a", "A")])
            .unwrap();
        assert_eq!(forward, reversed, "output must not depend on input order");
    }

    #[test]
    fn a_duplicate_uid_fails_the_render() {
        let err = renderer()
            .render(&[task("same", "First"), task("same", "Second")])
            .unwrap_err();
        assert!(matches!(err, RenderError::DuplicateUid { .. }), "{err:?}");
    }

    #[test]
    fn dtstamp_uses_last_modified_and_is_stable_between_renders() {
        let mut t = task("a", "One");
        t.last_modified = Some(Utc.with_ymd_and_hms(2026, 8, 29, 12, 0, 0).unwrap());
        let renderer = renderer();
        let first = renderer.render(std::slice::from_ref(&t)).unwrap();
        let second = renderer.render(std::slice::from_ref(&t)).unwrap();
        assert!(first.contains("DTSTAMP:20260829T120000Z"), "{first}");
        assert_eq!(first, second, "repeated renders must be byte-identical");
    }

    #[test]
    fn alarms_are_byte_identical_between_renders() {
        let mut t = task("a", "One");
        t.deadline = date("2026-08-30T14:30:00+04:00");
        let renderer = renderer();
        let first = renderer.render(std::slice::from_ref(&t)).unwrap();
        let second = renderer.render(std::slice::from_ref(&t)).unwrap();
        assert!(first.contains("BEGIN:VALARM"), "{first}");
        assert_eq!(first, second);
    }

    #[test]
    fn dtstamp_falls_back_to_the_process_timestamp() {
        let ics = renderer().render(&[task("a", "One")]).unwrap();
        assert!(ics.contains("DTSTAMP:20260101T000000Z"), "{ics}");
    }

    #[test]
    fn escapes_special_characters_and_preserves_unicode() {
        let ics = renderer()
            .render(&[task("a", "Купить: хлеб, молоко; сыр \\ и всё")])
            .unwrap();
        let unfolded = ics.replace("\r\n ", "");
        assert!(unfolded.contains("хлеб"), "unicode preserved: {unfolded}");
        assert!(unfolded.contains("\\,"), "comma escaped: {unfolded}");
        assert!(unfolded.contains(r"\;"), "semicolon escaped: {unfolded}");
    }

    #[test]
    fn folds_physical_lines_to_the_rfc_limit() {
        let long = "Очень длинное название задачи ".repeat(12);
        let ics = renderer().render(&[task("a", &long)]).unwrap();
        for line in ics.split("\r\n") {
            assert!(
                line.len() <= 75,
                "line of {} octets exceeds the RFC 5545 limit: {line}",
                line.len()
            );
        }
    }

    /// Parsed by a different crate than the one that produced it: a serializer
    /// validating its own output proves very little.
    #[test]
    fn output_is_accepted_by_an_independent_parser() {
        let mut done = task("b", "Done one");
        done.done = true;
        done.deadline = date("2026-08-30T00:00:00+04:00");
        let mut timed = task("a", "Timed one");
        timed.scheduled = date("2026-08-29T14:30:00+04:00");

        let ics = renderer().render(&[timed, done]).unwrap();

        let reader = ical::IcalParser::new(std::io::BufReader::new(ics.as_bytes()));
        let calendars: Vec<_> = reader.collect::<Result<Vec<_>, _>>().expect("parses");
        assert_eq!(calendars.len(), 1);
        let todos = &calendars[0].todos;
        assert_eq!(todos.len(), 2, "both tasks survive a round trip");

        let uids: Vec<_> = todos
            .iter()
            .filter_map(|todo| {
                todo.properties
                    .iter()
                    .find(|p| p.name == "UID")
                    .and_then(|p| p.value.clone())
            })
            .collect();
        assert_eq!(
            uids,
            vec![
                "a@anytype-task-exporter".to_string(),
                "b@anytype-task-exporter".to_string()
            ]
        );
    }

    #[test]
    fn a_timed_deadline_alarms_the_configured_lead_time_before_it() {
        let mut t = task("a", "One");
        // 14:30 Saratov == 10:30 UTC; 30 minutes earlier is 10:00 UTC.
        t.deadline = date("2026-08-30T14:30:00+04:00");
        let ics = renderer().render(&[t]).unwrap();
        assert!(ics.contains("BEGIN:VALARM"), "{ics}");
        assert!(ics.contains("ACTION:DISPLAY"), "{ics}");
        assert!(
            ics.contains("TRIGGER;VALUE=DATE-TIME:20260830T100000Z"),
            "{ics}"
        );
    }

    /// An all-day task starts at midnight, so a relative trigger would fire in
    /// the middle of the night. The alarm lands at a civil hour instead.
    #[test]
    fn an_all_day_deadline_alarms_at_the_configured_time_of_day() {
        let mut t = task("a", "One");
        t.deadline = date("2026-08-30T00:00:00+04:00");
        let ics = renderer().render(&[t]).unwrap();
        // 09:00 Saratov == 05:00 UTC on the same day.
        assert!(
            ics.contains("TRIGGER;VALUE=DATE-TIME:20260830T050000Z"),
            "{ics}"
        );
        assert!(!ics.contains("TRIGGER:-PT"), "no relative trigger: {ics}");
    }

    #[test]
    fn the_deadline_wins_over_the_scheduled_date() {
        let mut t = task("a", "One");
        t.scheduled = date("2026-08-20T00:00:00+04:00");
        t.deadline = date("2026-08-30T00:00:00+04:00");
        let ics = renderer().render(&[t]).unwrap();
        assert!(
            ics.contains("TRIGGER;VALUE=DATE-TIME:20260830T050000Z"),
            "{ics}"
        );
    }

    #[test]
    fn a_task_with_only_a_scheduled_date_still_alarms() {
        let mut t = task("a", "One");
        t.scheduled = date("2026-08-30T00:00:00+04:00");
        let ics = renderer().render(&[t]).unwrap();
        assert!(ics.contains("BEGIN:VALARM"), "{ics}");
    }

    #[test]
    fn a_completed_task_does_not_alarm() {
        let mut t = task("a", "One");
        t.deadline = date("2026-08-30T00:00:00+04:00");
        t.done = true;
        let ics = renderer().render(&[t]).unwrap();
        assert!(!ics.contains("BEGIN:VALARM"), "{ics}");
    }

    #[test]
    fn a_task_without_dates_does_not_alarm() {
        let ics = renderer().render(&[task("a", "One")]).unwrap();
        assert!(!ics.contains("BEGIN:VALARM"), "{ics}");
    }

    #[test]
    fn reminders_can_be_switched_off() {
        let mut t = task("a", "One");
        t.deadline = date("2026-08-30T00:00:00+04:00");
        let off = RemindersConfig {
            enabled: false,
            ..reminders()
        };
        let ics = renderer_with(off).render(&[t]).unwrap();
        assert!(!ics.contains("BEGIN:VALARM"), "{ics}");
    }

    #[test]
    fn the_alarm_survives_an_independent_parser() {
        let mut t = task("a", "One");
        t.deadline = date("2026-08-30T00:00:00+04:00");
        let ics = renderer().render(&[t]).unwrap();
        let reader = ical::IcalParser::new(std::io::BufReader::new(ics.as_bytes()));
        let calendars: Vec<_> = reader.collect::<Result<Vec<_>, _>>().expect("parses");
        let alarms = &calendars[0].todos[0].alarms;
        assert_eq!(alarms.len(), 1, "one alarm survives the round trip");
    }

    /// Several chosen lead times become several `VALARM`s on one `VTODO`,
    /// which RFC 5545 permits and which keeps the feed saying the same thing
    /// the push scheduler will do.
    #[test]
    fn per_task_lead_times_produce_one_alarm_each() {
        let mut t = task("a", "One");
        t.deadline = date("2026-09-03T18:00:00+04:00");
        t.reminder_leads = vec![chrono::Duration::hours(2), chrono::Duration::days(1)];

        let ics = renderer().render(&[t]).unwrap();

        assert!(
            ics.contains("TRIGGER;VALUE=DATE-TIME:20260902T140000Z"),
            "{ics}"
        );
        assert!(
            ics.contains("TRIGGER;VALUE=DATE-TIME:20260903T120000Z"),
            "{ics}"
        );
        let reader = ical::IcalParser::new(std::io::BufReader::new(ics.as_bytes()));
        let calendars: Vec<_> = reader.collect::<Result<Vec<_>, _>>().expect("parses");
        assert_eq!(calendars[0].todos[0].alarms.len(), 2);
    }

    #[test]
    fn an_empty_task_list_still_produces_a_valid_calendar() {
        let ics = renderer().render(&[]).unwrap();
        assert!(ics.contains("BEGIN:VCALENDAR"), "{ics}");
        assert!(!ics.contains("BEGIN:VTODO"), "{ics}");
        let reader = ical::IcalParser::new(std::io::BufReader::new(ics.as_bytes()));
        let calendars: Vec<_> = reader.collect::<Result<Vec<_>, _>>().expect("parses");
        assert_eq!(calendars.len(), 1);
        assert!(calendars[0].todos.is_empty());
    }
}
