//! Turns internal tasks into a complete `VCALENDAR` document.

use std::collections::BTreeMap;

use chrono::{DateTime, NaiveDateTime, TimeZone, Utc};
use icalendar::{
    Alarm, Calendar, CalendarDateTime, Component, DatePerhapsTime, EventLike, Property, Todo,
    TodoStatus, Trigger,
};

use crate::{
    config::{CalendarConfig, RemindersConfig},
    model::{CalendarValue, Task},
    reminder::reminders_for,
};

#[derive(Debug, thiserror::Error)]
pub enum RenderError {
    /// Two tasks produced one UID. Publishing that would make a calendar
    /// client silently drop one of them, so the whole render fails instead.
    #[error("duplicate UID {uid} generated by objects {first} and {second}")]
    DuplicateUid {
        uid: String,
        first: String,
        second: String,
    },
}

/// What a task's two dates become on the wire.
enum Schedule {
    Neither,
    Start(DatePerhapsTime),
    Due(DatePerhapsTime),
    Both {
        start: DatePerhapsTime,
        due: DatePerhapsTime,
    },
    /// Work planned after its deadline: the start is written, the deadline is
    /// described in words because the pair cannot be written literally.
    Overdue {
        start: DatePerhapsTime,
        deadline: String,
    },
}

pub struct VTodoRenderer {
    config: CalendarConfig,
    reminders: RemindersConfig,
    /// Used as `DTSTAMP` for tasks whose last-modified time Anytype did not
    /// report. Fixed for the life of the process so that repeated requests
    /// produce byte-identical output, which keeps the ETag stable.
    fallback_stamp: DateTime<Utc>,
}

impl VTodoRenderer {
    pub fn new(
        config: CalendarConfig,
        reminders: RemindersConfig,
        fallback_stamp: DateTime<Utc>,
    ) -> Self {
        Self {
            config,
            reminders,
            fallback_stamp,
        }
    }

    pub fn render(&self, tasks: &[Task]) -> Result<String, RenderError> {
        // Sorting by UID makes the output deterministic, so identical source
        // data always hashes to the same ETag.
        let mut by_uid: BTreeMap<String, &Task> = BTreeMap::new();
        for task in tasks {
            let uid = task.uid();
            if let Some(existing) = by_uid.get(&uid) {
                return Err(RenderError::DuplicateUid {
                    uid,
                    first: existing.object_id.clone(),
                    second: task.object_id.clone(),
                });
            }
            by_uid.insert(uid, task);
        }

        let mut calendar = Calendar::new();
        calendar
            .name(&self.config.name)
            .timezone(self.config.timezone.name())
            .append_property(Property::new("PRODID", "-//Anytype Task Exporter//EN"))
            .append_property(Property::new("VERSION", "2.0"))
            .append_property(Property::new("CALSCALE", "GREGORIAN"));

        for task in by_uid.values() {
            calendar.push(self.render_task(task));
        }

        Ok(calendar.to_string())
    }

    fn render_task(&self, task: &Task) -> Todo {
        let mut todo = Todo::new();
        todo.uid(&task.uid())
            .summary(&task.name)
            .timestamp(task.last_modified.unwrap_or(self.fallback_stamp));

        let tz = self.config.date_only_timezone;
        match self.schedule(
            task.scheduled.as_ref().map(|value| value.classify(tz)),
            task.deadline.as_ref().map(|value| value.classify(tz)),
        ) {
            Schedule::Neither => {}
            Schedule::Start(start) => {
                todo.starts(start);
            }
            Schedule::Due(due) => {
                todo.due(due);
            }
            Schedule::Both { start, due } => {
                todo.starts(start).due(due);
            }
            Schedule::Overdue { start, deadline } => {
                todo.starts(start).description(&deadline);
            }
        }

        if task.done {
            todo.status(TodoStatus::Completed).percent_complete(100);
            // No COMPLETED property: Anytype's checkbox records *that* a task
            // is done, not *when*. Substituting last-modified would invent a
            // timestamp the source never supplied.
        } else {
            todo.status(TodoStatus::NeedsAction).percent_complete(0);
        }

        if let Some(url) = &task.object_url {
            todo.url(url);
        }

        let mut todo = todo.done();
        for alarm in self.alarms_for(task) {
            todo.alarm(alarm);
        }
        todo
    }

    /// Builds the `VALARM`s, if any.
    ///
    /// Every trigger is an absolute instant. A relative trigger on a `VTODO`
    /// resolves against `DTSTART` unless `RELATED=END` is given, and an all-day
    /// task starts at midnight, so "30 minutes before" would fire at 23:30 the
    /// night before. Computing the instant here removes that ambiguity.
    fn alarms_for(&self, task: &Task) -> Vec<Alarm> {
        reminders_for(task, &self.config, &self.reminders)
            .into_iter()
            .map(|moment| {
                Alarm::display(
                    &task.name,
                    Trigger::DateTime(CalendarDateTime::Utc(moment.trigger_at)),
                )
                .done()
            })
            .collect()
    }

    /// Resolves the two source dates into a pair a calendar client will accept.
    ///
    /// RFC 5545 §3.6.2 requires `DUE` to share `DTSTART`'s value type and to be
    /// later in time than it. Anytype constrains neither, so three shapes need
    /// care: a date-only deadline against a timed start (the common one, since
    /// such a deadline means the *end* of its day while `VALUE=DATE` reads as
    /// the start), an all-day pair on a single day, and work genuinely planned
    /// after its deadline. Emitting the invalid pair is the worst option
    /// available — a client drops the task from the calendar altogether.
    fn schedule(
        &self,
        scheduled: Option<CalendarValue>,
        deadline: Option<CalendarValue>,
    ) -> Schedule {
        let (start, due) = match (scheduled, deadline) {
            (None, None) => return Schedule::Neither,
            (Some(start), None) => return Schedule::Start(self.to_calendar_date(start)),
            (None, Some(due)) => return Schedule::Due(self.to_calendar_date(due)),
            (Some(start), Some(due)) => (start, due),
        };

        // Planning work after its own deadline is legitimate — the deadline was
        // missed and the task is being done late — but iCalendar cannot say it.
        // The start survives because it is the date to act on, and the deadline
        // moves into DESCRIPTION rather than vanishing.
        if self.begins(start) >= self.expires(due) {
            return Schedule::Overdue {
                start: self.to_calendar_date(start),
                deadline: self.describe(due),
            };
        }

        match (start, due) {
            // One all-day value cannot precede another on the same day, and the
            // start would say nothing the deadline does not.
            (CalendarValue::AllDay(from), CalendarValue::AllDay(to)) if from == to => {
                Schedule::Due(self.to_calendar_date(due))
            }
            (CalendarValue::AllDay(_), CalendarValue::AllDay(_))
            | (CalendarValue::Instant(_), CalendarValue::Instant(_)) => Schedule::Both {
                start: self.to_calendar_date(start),
                due: self.to_calendar_date(due),
            },
            // Mixed value types with a sound order: express both as instants so
            // the deadline keeps its "by the end of that day" meaning instead of
            // collapsing onto midnight.
            _ => match (
                self.instant(self.begins(start)),
                self.instant(self.expires(due)),
            ) {
                (Some(start), Some(due)) => Schedule::Both {
                    start: DatePerhapsTime::DateTime(CalendarDateTime::Utc(start)),
                    due: DatePerhapsTime::DateTime(CalendarDateTime::Utc(due)),
                },
                // A DST gap swallowed one of the civil times; the deadline alone
                // is still valid and is the more important of the two.
                _ => Schedule::Due(self.to_calendar_date(due)),
            },
        }
    }

    /// The civil moment a value starts covering.
    fn begins(&self, value: CalendarValue) -> NaiveDateTime {
        match value {
            CalendarValue::AllDay(day) => day.and_hms_opt(0, 0, 0).expect("midnight exists"),
            CalendarValue::Instant(at) => at.with_timezone(&self.config.timezone).naive_local(),
        }
    }

    /// The last civil moment at which a value is still met. An all-day deadline
    /// runs to the end of its day, which is the whole reason a task planned for
    /// noon can share that day with it.
    fn expires(&self, value: CalendarValue) -> NaiveDateTime {
        match value {
            CalendarValue::AllDay(day) => day.and_hms_opt(23, 59, 59).expect("last second exists"),
            CalendarValue::Instant(at) => at.with_timezone(&self.config.timezone).naive_local(),
        }
    }

    fn instant(&self, local: NaiveDateTime) -> Option<DateTime<Utc>> {
        self.config
            .timezone
            .from_local_datetime(&local)
            .earliest()
            .map(|at| at.with_timezone(&Utc))
    }

    fn describe(&self, deadline: CalendarValue) -> String {
        match deadline {
            CalendarValue::AllDay(day) => format!("Дедлайн: {}", day.format("%d.%m.%Y")),
            CalendarValue::Instant(at) => format!(
                "Дедлайн: {}",
                at.with_timezone(&self.config.timezone)
                    .format("%d.%m.%Y %H:%M")
            ),
        }
    }

    fn to_calendar_date(&self, value: CalendarValue) -> DatePerhapsTime {
        match value {
            CalendarValue::AllDay(date) => DatePerhapsTime::Date(date),
            CalendarValue::Instant(dt) => DatePerhapsTime::DateTime(CalendarDateTime::Utc(dt)),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;
    use chrono_tz::Europe::Saratov;

    use crate::model::AnytypeDate;

    fn calendar_config() -> CalendarConfig {
        CalendarConfig {
            timezone: Saratov,
            name: "Anytype Tasks".into(),
            date_only_timezone: Saratov,
        }
    }

    fn reminders() -> RemindersConfig {
        RemindersConfig {
            enabled: true,
            lead_time: chrono::Duration::minutes(30),
            all_day_time: chrono::NaiveTime::from_hms_opt(9, 0, 0).unwrap(),
        }
    }

    fn renderer() -> VTodoRenderer {
        renderer_with(reminders())
    }

    fn renderer_with(reminders: RemindersConfig) -> VTodoRenderer {
        VTodoRenderer::new(
            calendar_config(),
            reminders,
            Utc.with_ymd_and_hms(2026, 1, 1, 0, 0, 0).unwrap(),
        )
    }

    fn task(id: &str, name: &str) -> Task {
        Task {
            object_id: id.into(),
            name: name.into(),
            scheduled: None,
            deadline: None,
            done: false,
            reminder_leads: Vec::new(),
            object_url: None,
            last_modified: None,
        }
    }

    fn date(raw: &str) -> Option<AnytypeDate> {
        AnytypeDate::parse(raw)
    }

    /// Observed live: Anytype happily holds "planned today at noon, due today",
    /// which is ordinary, but a date-only DUE reads as that day's *midnight* and
    /// the pair then looks backwards. Calino refused to display five such tasks.
    #[test]
    fn a_date_only_deadline_runs_to_the_end_of_its_day() {
        let mut t = task("ozon", "Проверить кредитку Ozon");
        t.scheduled = date("2026-08-28T12:00:00+04:00");
        t.deadline = date("2026-08-28T00:00:00+04:00");

        let ics = renderer().render(&[t]).unwrap();

        // Both as instants, so the types match and the order is sound.
        assert!(ics.contains("DTSTART:20260828T080000Z"), "{ics}");
        assert!(ics.contains("DUE:20260828T195959Z"), "{ics}");
        assert!(!ics.contains("VALUE=DATE:20260828"), "{ics}");
    }

    /// Missing a deadline and planning the work late is a real state, and one
    /// iCalendar cannot express. The actionable date is kept; the deadline is
    /// described rather than dropped.
    #[test]
    fn work_planned_after_its_deadline_keeps_the_date_to_act_on() {
        let mut t = task("late", "Сделай self-review статьи");
        t.scheduled = date("2026-07-28T19:00:00+04:00");
        t.deadline = date("2026-07-15T00:00:00+04:00");

        let ics = renderer().render(&[t]).unwrap();

        assert!(ics.contains("DTSTART:20260728T150000Z"), "{ics}");
        assert!(!ics.contains("\nDUE"), "{ics}");
        assert!(ics.contains("DESCRIPTION:Дедлайн: 15.07.2026"), "{ics}");
    }

    /// Two all-day values on one day cannot be ordered, and the start would say
    /// nothing the deadline does not.
    #[test]
    fn an_all_day_pair_on_one_day_is_written_as_the_deadline_alone() {
        let mut t = task("sber", "Проверить кредитку Сбера");
        t.scheduled = date("2026-08-31T00:00:00+04:00");
        t.deadline = date("2026-08-31T00:00:00+04:00");

        let ics = renderer().render(&[t]).unwrap();

        assert!(ics.contains("DUE;VALUE=DATE:20260831"), "{ics}");
        assert!(!ics.contains("DTSTART"), "{ics}");
    }

    #[test]
    fn emits_the_expected_calendar_properties() {
        let ics = renderer().render(&[task("a", "One")]).unwrap();
        assert!(ics.contains("VERSION:2.0"), "{ics}");
        assert!(ics.contains("PRODID:-//Anytype Task Exporter//EN"), "{ics}");
        assert!(ics.contains("CALSCALE:GREGORIAN"), "{ics}");
        assert!(ics.contains("X-WR-CALNAME:Anytype Tasks"), "{ics}");
        assert!(ics.contains("X-WR-TIMEZONE:Europe/Saratov"), "{ics}");
        assert!(ics.starts_with("BEGIN:VCALENDAR"), "{ics}");
        assert!(ics.trim_end().ends_with("END:VCALENDAR"), "{ics}");
    }

    #[test]
    fn an_active_task_needs_action() {
        let ics = renderer().render(&[task("a", "One")]).unwrap();
        assert!(ics.contains("STATUS:NEEDS-ACTION"), "{ics}");
        assert!(ics.contains("PERCENT-COMPLETE:0"), "{ics}");
    }

    #[test]
    fn a_done_task_is_completed() {
        let mut done = task("a", "One");
        done.done = true;
        let ics = renderer().render(&[done]).unwrap();
        assert!(ics.contains("STATUS:COMPLETED"), "{ics}");
        assert!(ics.contains("PERCENT-COMPLETE:100"), "{ics}");
    }

    /// Anytype records *that* a task is done, never *when*. Inventing the
    /// timestamp would be worse than omitting the property.
    #[test]
    fn never_fabricates_a_completed_timestamp() {
        let mut done = task("a", "One");
        done.done = true;
        done.last_modified = Some(Utc.with_ymd_and_hms(2026, 8, 29, 12, 0, 0).unwrap());
        let ics = renderer().render(&[done]).unwrap();
        assert!(!ics.contains("COMPLETED:"), "{ics}");
    }

    #[test]
    fn never_emits_recurrence() {
        let ics = renderer()
            .render(&[task("a", "One"), task("b", "Two")])
            .unwrap();
        assert!(!ics.contains("RRULE"), "{ics}");
        assert!(!ics.contains("RDATE"), "{ics}");
    }

    /// A `TZID` parameter would oblige the document to carry a matching
    /// `VTIMEZONE` component (RFC 5545 §3.6.5). Emitting UTC instants avoids
    /// the requirement entirely, so neither may ever appear.
    #[test]
    fn never_emits_tzid_or_vtimezone() {
        let mut t = task("a", "One");
        t.scheduled = date("2026-08-29T14:30:00+04:00");
        t.deadline = date("2026-08-30T18:00:00+04:00");
        let ics = renderer().render(&[t]).unwrap();
        assert!(!ics.contains("TZID="), "{ics}");
        assert!(!ics.contains("BEGIN:VTIMEZONE"), "{ics}");
    }

    #[test]
    fn midnight_becomes_a_date_value() {
        let mut t = task("a", "One");
        t.scheduled = date("2026-08-29T00:00:00+04:00");
        t.deadline = date("2026-08-30T00:00:00+04:00");
        let ics = renderer().render(&[t]).unwrap();
        assert!(ics.contains("DTSTART;VALUE=DATE:20260829"), "{ics}");
        assert!(ics.contains("DUE;VALUE=DATE:20260830"), "{ics}");
    }

    #[test]
    fn a_time_of_day_becomes_a_utc_instant() {
        let mut t = task("a", "One");
        t.scheduled = date("2026-08-29T14:30:00+04:00");
        let ics = renderer().render(&[t]).unwrap();
        assert!(ics.contains("DTSTART:20260829T103000Z"), "{ics}");
    }

    #[test]
    fn a_task_without_dates_stays_undated() {
        let ics = renderer().render(&[task("a", "One")]).unwrap();
        assert!(!ics.contains("DTSTART"), "{ics}");
        assert!(!ics.contains("DUE"), "{ics}");
    }

    #[test]
    fn components_are_ordered_by_uid_regardless_of_input_order() {
        let forward = renderer()
            .render(&[task("a", "A"), task("b", "B"), task("c", "C")])
            .unwrap();
        let reversed = renderer()
            .render(&[task("c", "C"), task("b", "B"), task("a", "A")])
            .unwrap();
        assert_eq!(forward, reversed, "output must not depend on input order");
    }

    #[test]
    fn a_duplicate_uid_fails_the_render() {
        let err = renderer()
            .render(&[task("same", "First"), task("same", "Second")])
            .unwrap_err();
        assert!(matches!(err, RenderError::DuplicateUid { .. }), "{err:?}");
    }

    #[test]
    fn dtstamp_uses_last_modified_and_is_stable_between_renders() {
        let mut t = task("a", "One");
        t.last_modified = Some(Utc.with_ymd_and_hms(2026, 8, 29, 12, 0, 0).unwrap());
        let renderer = renderer();
        let first = renderer.render(std::slice::from_ref(&t)).unwrap();
        let second = renderer.render(std::slice::from_ref(&t)).unwrap();
        assert!(first.contains("DTSTAMP:20260829T120000Z"), "{first}");
        assert_eq!(first, second, "repeated renders must be byte-identical");
    }

    #[test]
    fn dtstamp_falls_back_to_the_process_timestamp() {
        let ics = renderer().render(&[task("a", "One")]).unwrap();
        assert!(ics.contains("DTSTAMP:20260101T000000Z"), "{ics}");
    }

    #[test]
    fn escapes_special_characters_and_preserves_unicode() {
        let ics = renderer()
            .render(&[task("a", "Купить: хлеб, молоко; сыр \\ и всё")])
            .unwrap();
        let unfolded = ics.replace("\r\n ", "");
        assert!(unfolded.contains("хлеб"), "unicode preserved: {unfolded}");
        assert!(unfolded.contains("\\,"), "comma escaped: {unfolded}");
        assert!(unfolded.contains(r"\;"), "semicolon escaped: {unfolded}");
    }

    #[test]
    fn folds_physical_lines_to_the_rfc_limit() {
        let long = "Очень длинное название задачи ".repeat(12);
        let ics = renderer().render(&[task("a", &long)]).unwrap();
        for line in ics.split("\r\n") {
            assert!(
                line.len() <= 75,
                "line of {} octets exceeds the RFC 5545 limit: {line}",
                line.len()
            );
        }
    }

    /// Parsed by a different crate than the one that produced it: a serializer
    /// validating its own output proves very little.
    #[test]
    fn output_is_accepted_by_an_independent_parser() {
        let mut done = task("b", "Done one");
        done.done = true;
        done.deadline = date("2026-08-30T00:00:00+04:00");
        let mut timed = task("a", "Timed one");
        timed.scheduled = date("2026-08-29T14:30:00+04:00");

        let ics = renderer().render(&[timed, done]).unwrap();

        let reader = ical::IcalParser::new(std::io::BufReader::new(ics.as_bytes()));
        let calendars: Vec<_> = reader.collect::<Result<Vec<_>, _>>().expect("parses");
        assert_eq!(calendars.len(), 1);
        let todos = &calendars[0].todos;
        assert_eq!(todos.len(), 2, "both tasks survive a round trip");

        let uids: Vec<_> = todos
            .iter()
            .filter_map(|todo| {
                todo.properties
                    .iter()
                    .find(|p| p.name == "UID")
                    .and_then(|p| p.value.clone())
            })
            .collect();
        assert_eq!(
            uids,
            vec![
                "a@anytype-task-exporter".to_string(),
                "b@anytype-task-exporter".to_string()
            ]
        );
    }

    #[test]
    fn a_timed_deadline_alarms_the_configured_lead_time_before_it() {
        let mut t = task("a", "One");
        // 14:30 Saratov == 10:30 UTC; 30 minutes earlier is 10:00 UTC.
        t.deadline = date("2026-08-30T14:30:00+04:00");
        let ics = renderer().render(&[t]).unwrap();
        assert!(ics.contains("BEGIN:VALARM"), "{ics}");
        assert!(ics.contains("ACTION:DISPLAY"), "{ics}");
        assert!(
            ics.contains("TRIGGER;VALUE=DATE-TIME:20260830T100000Z"),
            "{ics}"
        );
    }

    /// An all-day task starts at midnight, so a relative trigger would fire in
    /// the middle of the night. The alarm lands at a civil hour instead.
    #[test]
    fn an_all_day_deadline_alarms_at_the_configured_time_of_day() {
        let mut t = task("a", "One");
        t.deadline = date("2026-08-30T00:00:00+04:00");
        let ics = renderer().render(&[t]).unwrap();
        // 09:00 Saratov == 05:00 UTC on the same day.
        assert!(
            ics.contains("TRIGGER;VALUE=DATE-TIME:20260830T050000Z"),
            "{ics}"
        );
        assert!(!ics.contains("TRIGGER:-PT"), "no relative trigger: {ics}");
    }

    #[test]
    fn the_deadline_wins_over_the_scheduled_date() {
        let mut t = task("a", "One");
        t.scheduled = date("2026-08-20T00:00:00+04:00");
        t.deadline = date("2026-08-30T00:00:00+04:00");
        let ics = renderer().render(&[t]).unwrap();
        assert!(
            ics.contains("TRIGGER;VALUE=DATE-TIME:20260830T050000Z"),
            "{ics}"
        );
    }

    #[test]
    fn a_task_with_only_a_scheduled_date_still_alarms() {
        let mut t = task("a", "One");
        t.scheduled = date("2026-08-30T00:00:00+04:00");
        let ics = renderer().render(&[t]).unwrap();
        assert!(ics.contains("BEGIN:VALARM"), "{ics}");
    }

    #[test]
    fn a_completed_task_does_not_alarm() {
        let mut t = task("a", "One");
        t.deadline = date("2026-08-30T00:00:00+04:00");
        t.done = true;
        let ics = renderer().render(&[t]).unwrap();
        assert!(!ics.contains("BEGIN:VALARM"), "{ics}");
    }

    #[test]
    fn a_task_without_dates_does_not_alarm() {
        let ics = renderer().render(&[task("a", "One")]).unwrap();
        assert!(!ics.contains("BEGIN:VALARM"), "{ics}");
    }

    #[test]
    fn reminders_can_be_switched_off() {
        let mut t = task("a", "One");
        t.deadline = date("2026-08-30T00:00:00+04:00");
        let off = RemindersConfig {
            enabled: false,
            ..reminders()
        };
        let ics = renderer_with(off).render(&[t]).unwrap();
        assert!(!ics.contains("BEGIN:VALARM"), "{ics}");
    }

    #[test]
    fn the_alarm_survives_an_independent_parser() {
        let mut t = task("a", "One");
        t.deadline = date("2026-08-30T00:00:00+04:00");
        let ics = renderer().render(&[t]).unwrap();
        let reader = ical::IcalParser::new(std::io::BufReader::new(ics.as_bytes()));
        let calendars: Vec<_> = reader.collect::<Result<Vec<_>, _>>().expect("parses");
        let alarms = &calendars[0].todos[0].alarms;
        assert_eq!(alarms.len(), 1, "one alarm survives the round trip");
    }

    /// Several chosen lead times become several `VALARM`s on one `VTODO`,
    /// which RFC 5545 permits and which keeps the feed saying the same thing
    /// the push scheduler will do.
    #[test]
    fn per_task_lead_times_produce_one_alarm_each() {
        let mut t = task("a", "One");
        t.deadline = date("2026-09-03T18:00:00+04:00");
        t.reminder_leads = vec![chrono::Duration::hours(2), chrono::Duration::days(1)];

        let ics = renderer().render(&[t]).unwrap();

        assert!(
            ics.contains("TRIGGER;VALUE=DATE-TIME:20260902T140000Z"),
            "{ics}"
        );
        assert!(
            ics.contains("TRIGGER;VALUE=DATE-TIME:20260903T120000Z"),
            "{ics}"
        );
        let reader = ical::IcalParser::new(std::io::BufReader::new(ics.as_bytes()));
        let calendars: Vec<_> = reader.collect::<Result<Vec<_>, _>>().expect("parses");
        assert_eq!(calendars[0].todos[0].alarms.len(), 2);
    }

    #[test]
    fn an_empty_task_list_still_produces_a_valid_calendar() {
        let ics = renderer().render(&[]).unwrap();
        assert!(ics.contains("BEGIN:VCALENDAR"), "{ics}");
        assert!(!ics.contains("BEGIN:VTODO"), "{ics}");
        let reader = ical::IcalParser::new(std::io::BufReader::new(ics.as_bytes()));
        let calendars: Vec<_> = reader.collect::<Result<Vec<_>, _>>().expect("parses");
        assert_eq!(calendars.len(), 1);
        assert!(calendars[0].todos.is_empty());
    }
}
